env:
  browser: true
  node: true
extends:
  - bayathy

parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true

rules:
  "import/no-unresolved": off
  "unicorn/prevent-abbreviations": off
  "@typescript-eslint/no-unused-vars": "error"
overrides:
  - files: "**/*.@(stories|test).tsx"
    rules:
      "@typescript-eslint/no-unused-vars": off
